spring:
  application:
    name: ${dubbo.application.name}
server:
  port: 8082

dubbo:
  application:
    name: annotation-dubbo-provider # 提供方应用信息，用于计算依赖关系
  registry:
    protocol: zookeeper # 注册中心类型
    address: zookeeper://127.0.0.1:2181 # 注册中心地址
  protocol:
    name: dubbo # 暴露服务的方式
    port: 20881 # 暴露服务的端口