spring:
  application:
    name: ${dubbo.application.name}

dubbo:
  application:
    name: annotation-dubbo-consumer # 提供方应用信息，用于计算依赖关系
  registry:
    protocol: zookeeper # 注册中心类型
    address: zookeeper://127.0.0.1:2181 # 注册中心地址